"""
ConsultationSummary model — stores an LLM-generated human-readable summary
of a doctor-patient consultation.

The summary text is stored exactly as generated by the LLM — no structured
field extraction. It covers illness, duration, medications, diet, sleep,
water intake, tests, follow-ups, and any other advice discussed.
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin


class ConsultationSummary(TimestampMixin, Base):
    """
    Stores a single LLM-generated consultation summary per meeting.

    - Auto-generated after the AI extraction pipeline completes.
    - The full summary text is stored as-is from the LLM response.
    - Both the patient and the attending doctor can view it.
    - On next visit, the doctor sees the patient's full consultation history.
    """

    __tablename__ = "consultation_summaries"

    # ── Primary Key ──────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # ── Foreign Keys ─────────────────────────────────────────────────────
    meeting_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("meetings.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Summary Content ──────────────────────────────────────────────────
    summary_text: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, default=None,
    )

    # ── Processing Metadata ──────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", server_default="pending",
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, default=None,
    )
    llm_model_used: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, default=None,
    )
    processing_time_ms: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True, default=None,
    )

    # ── Relationships ────────────────────────────────────────────────────
    meeting = relationship("Meeting", foreign_keys=[meeting_id], lazy="selectin")
    doctor = relationship("User", foreign_keys=[doctor_id], lazy="selectin")
    patient = relationship("User", foreign_keys=[patient_id], lazy="selectin")

    def __repr__(self) -> str:
        return (
            f"<ConsultationSummary id={self.id} meeting_id={self.meeting_id} "
            f"status={self.status}>"
        )
